### ISSUE TITLE
[BUG]run bkr command failed with 'AttributeError: module 'ssl' has no attribute 'wrap_socket''

### ISSUE THREAD

**Issue by HouMinXi** [beaker-project/beaker#188]
**Describe the bug**  
update system from fedora38 to fedora39 and run bkr failed

**Version-Release number**  
kernel version: 6.5.11-300.fc39.x86_64
bkr package: beaker-client-28.4-1.fc39eng.noarch

**To Reproduce**  
1. run bkr whoami

**Actual behavior**  
$ bkr whoami
Traceback (most recent call last):
  File "/usr/bin/bkr", line 33, in <module>
    sys.exit(load_entry_point('beaker-client==28.4', 'console_scripts', 'bkr')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/bkr/client/main.py", line 113, in main
    return cmd.run(*cmd_args, **cmd_opts.__dict__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/bkr/client/commands/cmd_whoami.py", line 57, in run
    self.set_hub(**kwargs)
  File "/usr/lib/python3.12/site-packages/bkr/client/__init__.py", line 84, in set_hub
    self.container.set_hub(username, password, auto_login=self.requires_login,
  File "/usr/lib/python3.12/site-packages/bkr/client/command.py", line 328, in set_hub
    self.hub = HubProxy(conf=self.conf, auto_login=auto_login)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/bkr/common/hub.py", line 87, in __init__
    self._login()
  File "/usr/lib/python3.12/site-packages/bkr/common/hub.py", line 114, in _login
    login_method()
  File "/usr/lib/python3.12/site-packages/bkr/common/hub.py", line 214, in _login_krbv
    self._hub.auth.login_krbv(req_enc, proxyuser)
  File "/usr/lib64/python3.12/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/xmlrpc/client.py", line 1461, in __request
    response = self.__transport.request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/bkr/common/xmlrpc3.py", line 470, in request
    result = transport_class.request(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/bkr/common/xmlrpc3.py", line 368, in single_request
    http_con = self.send_request(host, handler, request_body, False)  # pylint: disable=too-many-function-args
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/xmlrpc/client.py", line 1279, in send_request
    connection = self.make_connection(host)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/bkr/common/xmlrpc3.py", line 436, in make_connection
    conn = TimeoutProxyHTTPS(host, **self.proxy_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/bkr/common/xmlrpc3.py", line 144, in __init__
    TimeoutHTTPSProxyConnection.__init__(self, host, proxy, port, proxy_user, proxy_password,
  File "/usr/lib/python3.12/site-packages/bkr/common/xmlrpc3.py", line 96, in __init__
    self.connect()
  File "/usr/lib/python3.12/site-packages/bkr/common/xmlrpc3.py", line 119, in connect
    self.sock = ssl.wrap_socket(self.sock, keyfile=self.key_file, certfile=self.cert_file)
                ^^^^^^^^^^^^^^^
AttributeError: module 'ssl' has no attribute 'wrap_socket'

**Expected behavior**  
show username as well

**Screenshots**  

**Additional context**  
https://docs.python.org/3.12/whatsnew/3.12.html#ssl
python3.12 remove the ssl.wrap_socket() function.

**Comment by StykMartin** [comment]
Looks good overall. It doesn't make much sense to fix this in xmlrpc2.py since it's only loaded when using Python 2, but I don't mind. We will ship this with the 29 release. And we need to fix the test suite (or create one? :sigh:)
