### ISSUE TITLE
[BUG] Unit Tests for LC are failing

### ISSUE THREAD

**Issue by StykMartin** [beaker-project/beaker#205]
**Describe the bug**  
Tests for concurrency are failing for the lab controller. This is quite a big deal as this part is part is using in provisioning to handle power commands.

**Version-Release number**  

- 28
- 29
- python-3

**To Reproduce**  

Run unit tests for the Lab Controller based on the environment defined in the spec file.
All my results are produced on x86_64 and aarch64 containers. Failure is the same everywhere.

**Actual behavior**  
```
======================================================================
FAIL: test_orphan_child_is_killed_when_parent_exits (bkr.labcontroller.test_async.SubprocessTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/beaker/beaker/LabController/src/bkr/labcontroller/test_async.py", line 131, in test_orphan_child_is_killed_when_parent_exits
    greenlet.get(block=False)
  File "/usr/lib64/python2.7/site-packages/gevent/greenlet.py", line 454, in get
    self._raise_exception()
  File "/usr/lib64/python2.7/site-packages/gevent/greenlet.py", line 171, in _raise_exception
    reraise(*self.exc_info)
  File "/usr/lib64/python2.7/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/__w/beaker/beaker/LabController/src/bkr/labcontroller/test_async.py", line 127, in _test
    self._assert_process_group_is_removed(p.pid)
  File "/__w/beaker/beaker/LabController/src/bkr/labcontroller/test_async.py", line 36, in _assert_process_group_is_removed
    self.fail("The process group should've already been removed")
  File "/usr/lib64/python2.7/unittest/case.py", line 450, in fail
    raise self.failureException(msg)
AssertionError: The process group should've already been removed


======================================================================
FAIL: test_process_group_is_killed_on_leader_timeout (bkr.labcontroller.test_async.SubprocessTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/beaker/beaker/LabController/src/bkr/labcontroller/test_async.py", line 102, in test_process_group_is_killed_on_leader_timeout
    greenlet.get(block=False)
  File "/usr/lib64/python2.7/site-packages/gevent/greenlet.py", line 454, in get
    self._raise_exception()
  File "/usr/lib64/python2.7/site-packages/gevent/greenlet.py", line 171, in _raise_exception
    reraise(*self.exc_info)
  File "/usr/lib64/python2.7/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/__w/beaker/beaker/LabController/src/bkr/labcontroller/test_async.py", line 98, in _test
    self._assert_process_group_is_removed(p.pid)
  File "/__w/beaker/beaker/LabController/src/bkr/labcontroller/test_async.py", line 36, in _assert_process_group_is_removed
    self.fail("The process group should've already been removed")
  File "/usr/lib64/python2.7/unittest/case.py", line 450, in fail
    raise self.failureException(msg)
AssertionError: The process group should've already been removed

----------------------------------------------------------------------

**Comment by StykMartin** [comment]
```
test_orphan_child_is_killed_when_parent_exits (bkr.labcontroller.test_async.SubprocessTest) ... ok
test_process_group_is_killed_on_leader_timeout (bkr.labcontroller.test_async.SubprocessTest) ... ok
```

From Release 29 build on bare-metal running mock.
