### ISSUE TITLE
Migrate from `pkg_resources` to `importlib.resources`/`importlib.metadata`

### ISSUE THREAD

**Issue by LecrisUT** [beaker-project/beaker#232]
It would be best to migrate away from `setuptools` dependency, if nothing else this requires a wide range of `setuptools` versions that have to be supported from rawhide to epel.

**Comment by psss** [comment]
Hi! Seems the latest `setuptools` have already deprecated usage of `pkg_resources`. Could you please update the code so that individual project don't have to pin old `setuptools` versions?

**Comment by hrnciar** [comment]
Hi, thanks for looking into this. I've started to work on updating setuptools to the latest version in Fedora.

**Comment by LecrisUT** [comment]
@StykMartin was this not yet released on `rawhide`?
```python
>>> from mrack.providers.beaker import BeakerProvider
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    from mrack.providers.beaker import BeakerProvider
  File "/usr/lib/python3.14/site-packages/mrack/providers/beaker.py", line 27, in <module>
    from bkr.client import BeakerJob, BeakerRecipe, BeakerRecipeSet
  File "/usr/lib/python3.14/site-packages/bkr/client/__init__.py", line 17, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by StykMartin** [comment]
Nope, I didn't release it. I'll backport it to release-29 branch and push it to rawhide.

**Comment by StykMartin** [comment]
@LecrisUT patch should be in Rawhide. We still require setuptools, but that will be my next target. At least for now, you don't need to lock down the version.
